sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t levanderia/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true levanderia/react-test npm test

after_success:
    - docker build -t levanderia/multi-client ./client
    - docker build -t levanderia/multi-nginx ./nginx
    - docker build -t levanderia/multi-server ./server
    - docker build -t levanderia/multi-worker ./worker  
    #log in to the docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push levanderia/multi-client
    - docker push levanderia/multi-nginx
    - docker push levanderia/multi-server
    - docker push levanderia/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: Multi-Docker-env
    bucket_name: elasticbeanstalk-us-east-2-309236198112
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

