sudo: required
services:
    - docker

before_install:
    - docker build -t levanderia/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run levanderia/react-test npm test -- --coverage

after_success:
    - docker build -t levanderia/multi-client ./client
    - docker build -t levanderia/multi-nginx ./nginx
    - docker build -t levanderia/multi-server ./server
    - docker build -t levanderia/multi-worker ./worker  
